- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - openstack-python3-victoria-jobs-neutron
      - openstack-python3-victoria-jobs
      - openstack-cover-jobs
    check:
      jobs:
        - vmware-tox-lower-constraints
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py36:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py37:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py38:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-cover:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
            voting: false
    gate:
      queue: vmware-nsx
      jobs:
        - vmware-tox-lower-constraints
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py36:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py37:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py38:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
              - openstack/octavia

- job:
    name: vmware-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    timeout: 5400
    required-projects:
      - openstack/neutron
      - x/networking-l2gw
      - openstack/networking-sfc
      - x/vmware-nsxlib
      - openstack/neutron-dynamic-routing
      - openstack/neutron-vpnaas
      - x/tap-as-a-service
      - openstack/octavia
