- job:
    name: vmware-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    timeout: 5400
    required-projects:
      - openstack/neutron
      - openstack/networking-l2gw
      - openstack/networking-sfc
      - openstack/neutron-lbaas
      - x/vmware-nsxlib
      - openstack/neutron-fwaas
      - openstack/neutron-dynamic-routing
      - openstack/neutron-vpnaas
      - x/tap-as-a-service
- project:
    check:
      jobs:
        - vmware-tox-lower-constraints
    gate:
      jobs:
        - vmware-tox-lower-constraints