- project:
    templates:
      - build-openstack-docs-pti
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
        - openstack-tox-py35:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
    gate:
      queue: vmware-nsx
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
        - openstack-tox-py35:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - openstack/neutron-lbaas
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - x/tap-as-a-service
