- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - openstack-python-jobs-neutron
      - openstack-python3-train-jobs
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py36:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py37:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
    gate:
      queue: vmware-nsx
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py27:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py36:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
        - openstack-tox-py37:
            timeout: 5400
            required-projects:
              - openstack/neutron
              - x/networking-l2gw
              - openstack/networking-sfc
              - x/vmware-nsxlib
              - openstack/neutron-fwaas
              - openstack/neutron-dynamic-routing
              - openstack/neutron-vpnaas
              - openstack/tap-as-a-service
              - openstack/octavia
